// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4PVdjP3sRJ5uN7yP3_sPtEeTNyfBKLXw',
    appId: '1:844363885696:web:335c3dd3ff0ca019ac4a65',
    messagingSenderId: '844363885696',
    projectId: 'findmypad-c4a6a',
    authDomain: 'findmypad-c4a6a.firebaseapp.com',
    storageBucket: 'findmypad-c4a6a.firebasestorage.app',
    measurementId: 'G-2Z00G1W5WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMmKvVxgShIkkIeeVup4XOYA_iuN27tDw',
    appId: '1:844363885696:android:59dbf184fbf4f3dfac4a65',
    messagingSenderId: '844363885696',
    projectId: 'findmypad-c4a6a',
    storageBucket: 'findmypad-c4a6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi33AQYKF2H5nLgXTr4E67oPYxgqF5xzw',
    appId: '1:844363885696:ios:f33a6eb5ab8a1469ac4a65',
    messagingSenderId: '844363885696',
    projectId: 'findmypad-c4a6a',
    storageBucket: 'findmypad-c4a6a.firebasestorage.app',
    iosBundleId: 'com.example.findmypad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi33AQYKF2H5nLgXTr4E67oPYxgqF5xzw',
    appId: '1:844363885696:ios:f33a6eb5ab8a1469ac4a65',
    messagingSenderId: '844363885696',
    projectId: 'findmypad-c4a6a',
    storageBucket: 'findmypad-c4a6a.firebasestorage.app',
    iosBundleId: 'com.example.findmypad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4PVdjP3sRJ5uN7yP3_sPtEeTNyfBKLXw',
    appId: '1:844363885696:web:1a3a6af90f982ee5ac4a65',
    messagingSenderId: '844363885696',
    projectId: 'findmypad-c4a6a',
    authDomain: 'findmypad-c4a6a.firebaseapp.com',
    storageBucket: 'findmypad-c4a6a.firebasestorage.app',
    measurementId: 'G-FPW1KFRQXQ',
  );
}
